// Code generated by goctl. DO NOT EDIT.
package types

type ExampleReq struct {
	Username string `form:"username"`                    //用户名
	Age      int    `form:"age,optional"`                //年龄可选
	Content  string `form:"content,options="Hello"|"Hi"` //请求内容，枚举
}

type ExampleResp struct {
	Content string `json:"content"`
}
