// Code generated by goctl. DO NOT EDIT!
// Source: example.proto

package example

import (
	"context"

	"example/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExampleReply = pb.ExampleReply
	ExampleReq   = pb.ExampleReq

	Example interface {
		GetContentByUsername(ctx context.Context, in *ExampleReq, opts ...grpc.CallOption) (*ExampleReply, error)
	}

	defaultExample struct {
		cli zrpc.Client
	}
)

func NewExample(cli zrpc.Client) Example {
	return &defaultExample{
		cli: cli,
	}
}

func (m *defaultExample) GetContentByUsername(ctx context.Context, in *ExampleReq, opts ...grpc.CallOption) (*ExampleReply, error) {
	client := pb.NewExampleClient(m.cli.Conn())
	return client.GetContentByUsername(ctx, in, opts...)
}
