// Code generated by goctl. DO NOT EDIT!
// Source: example.proto

package server

import (
	"context"

	"example/rpc/internal/logic"
	"example/rpc/internal/svc"
	"example/rpc/pb"
)

type ExampleServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedExampleServer
}

func NewExampleServer(svcCtx *svc.ServiceContext) *ExampleServer {
	return &ExampleServer{
		svcCtx: svcCtx,
	}
}

func (s *ExampleServer) GetContentByUsername(ctx context.Context, in *pb.ExampleReq) (*pb.ExampleReply, error) {
	l := logic.NewGetContentByUsernameLogic(ctx, s.svcCtx)
	return l.GetContentByUsername(in)
}
